Домашняя работа по Асинхронность. Работа с сетью. ДЗ 11
htmlacademy-javascript/2044413-kekstagram-simple-27 pull request #8
Opened 2022-11-15 12:58 UTC by dkhodas

2022-11-15 21:03 UTC, KletskovG requested changes

2022-11-15 21:03 UTC, KletskovG commented on js/api.js
> +// WorkWithServer.js - модуль для работы с настоящим сервером
комментарий с неактуальным названием

2022-11-15 21:03 UTC, KletskovG commented on js/api.js
> +        throw new Error();
Будет лучше сделать просто вызов `onError()`

Не стоит лишний раз бросать ошибку, когда можно без этого обойтись

2022-11-15 21:03 UTC, KletskovG commented on js/api.js
> +    .catch(() => onError());
Тут можно сделать просто `.catch(onError)`

2022-11-15 21:03 UTC, KletskovG commented on js/api.js
> +    .finally(() => onFinally());
До того момента, пока использование onSuccess, onError и onFinally без аргументов стоит сделать просто

```js
.then(onSuccess)
.catch(onError)
.finally(onFinally);
```

2022-11-15 21:03 UTC, KletskovG commented on js/constants.js
> +export const STEP_SCALE_PICTURE_VALUE = 25;
Для этих переменных обязательно стоит сделать перечисление

```js
const Scale = {
   min: 25,
   max: 100,
   step: 25
}
```

2022-11-15 21:03 UTC, KletskovG commented on js/main.js
> +//   });
В финальной версии проекта не должно быть подобных комментариев, только какое-то описание строчек, если тебе это необходимо

2022-11-15 21:22 UTC, KletskovG commented
Комментарии по проекту, что нужно поправить перед допуском

- Сейчас вообще не работает выбор глубины эффекты
- Форма с фотографией не должна закрываться по esc
- Если при загрузке фотографии сервер ответит с ошибкой (Ошибку можно сэмулировать, если сломать ссылку на сервер), то все равно покажется сообщение, что фотография успешно загружена - https://disk.yandex.ru/i/uLFT0YNNRDRAqg

- `workWithForm.js` - название файла не соответствует критерию https://up.htmlacademy.ru/javascript/27/criteries#b19, а так же стоит подыскать более подходящее название. Можно просто `form.js`
- Все переменные, в которых содержатся html-элементы, должны на конце содержать el или element (на проверке Мише писали замечания по этому поводу )
- в `utils.js` сейчас есть код, который не используется
- Все функции, которые сейчас передаются в `addEventListener`, должны содержать в названии либо `on` в начале, либо `handler` в конце, сейчас у тебя довольно много таких мест, все не буду перечислять - посмотри внимательно, пожалуйста
-  `zoomImage(100);` - вот тут давай в константу вынесем 
- ```js
if (successModal) {
    const successModalContent = successModal.querySelector('.success__inner');

    if(successModalContent.contains(evt.target) === false) {
      successModal.remove();
    }
  }

  if (errorModal) {
    const errroModalContent = errorModal.querySelector('.error__inner');

    if(errroModalContent.contains(evt.target) === false) {
      errorModal.remove();
    }
  }
``` 
   вот тут вместо `=== false` лучше просто сделать `!successModalContent.contains(evt.target)`, так как есть критерий 
   "Условия упрощены"
- в `main.js` есть код, который не используется
- `formValidate.js` - в названии должен быть дефис
- `effects.js` - есть код, который не используется
- `data.js` - по идее этот файл сейчас вообще не нужен, его стоит удалить

2022-11-16 20:17 UTC, dkhodas commented on js/api.js
> +        throw new Error();
я бросаю ошибку, чтобы прервать выполнение следующих "then"

2022-11-16 20:19 UTC, dkhodas commented on js/api.js
> +    .catch(() => onError());
я знаю, а это обязательное требование?
Просто сейчас мне понятнее такой синтаксис

2022-11-16 20:19 UTC, dkhodas commented on js/api.js
> +    .finally(() => onFinally());
я знаю, а это обязательное требование?
Просто сейчас мне понятнее такой синтаксис

2022-11-17 13:37 UTC, dkhodas commented on js/api.js
> +// WorkWithServer.js - модуль для работы с настоящим сервером
поправила!

2022-11-20 18:19 UTC, KletskovG approved these changes

2022-11-20 18:19 UTC, KletskovG commented on js/effects.js
> +    }
Вот тут лучше сделать 

```js
if (effect.name === 'none' && sliderElement.noUiSlider)  {

} else {
}
```

2022-11-20 18:43 UTC, merged